apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd_teste
  labels:
    app: sd_teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd_teste
  template:
    metadata:
      labels:
        app: sd_teste
    spec:
      containers:
      - name: sd_teste
        image: marioafonso10/projetoimg:v1
        ports:
        - containerPort: 3000