apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto
  labels:
    app: projeto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto
  template:
    metadata:
      labels:
        app: projeto
    spec:
      containers:
      - name: projeto
        image: marioafonso10/projetoimg:v1
        ports:
        - containerPort: 3000