apiVersion: v1
kind: Service
metadata:
  name: sd_teste
  labels:
    app: sd_teste
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: sd_teste