apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste
  labels:
    app: teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste
  template:
    metadata:
      labels:
        app: teste
    spec:
      containers:
      - name: teste
        image: marioafonso10/projetoimg:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: teste
  labels:
    app: teste
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: teste
