apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd
  labels:
    app: sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd
  template:
    metadata:
      labels:
        app: sd
    spec:
      containers:
      - name: sd
        image: kbaras/projetosd:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sd
  labels:
    app: sd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sd
