apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd_project
  labels:
    app: sd_project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd_project
  template:
    metadata:
      labels:
        app: sd_project
    spec:
      containers:
      - name: sd_project
        image: marioafonso10/projetoimg:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sd_project
  labels:
    app: sd_project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sd_project
