apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd
  labels:
    app: sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd
  template:
    metadata:
      labels:
        app: sd
    spec:
      containers:
      - name: sd
        image: projectsd.azurecr.io/app:v1
        ports:
        - containerPort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: sd
  labels:
    app: sd
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30001
  selector:
    app: sd