name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: use context
      run: |
        kubectl config use-context docker-desktop
    - name: apply the yaml file
      run: |
        kubectl apply -f deploy-and-service.yaml
