name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: marioafonso10
          password: dckr_pat_DsyR4424O72VR1g7IPMuvh4YB1I

      - name: Build and push image
        run: |
          docker buildx build --push --platform linux/arm/v7 --tag marioafonso10/projetosdteste .
